### ISSUE TITLE
[Question] on update events

### ISSUE THREAD

**Issue by ferllings** [brutella/hap#12]
Hello,

I would like some clarifications about the update events:
Whats the difference between: OnValueRemoteUpdate, OnValueUpdate and OnSetRemoteValue?

**Comment by brutella** [comment]
- OnValueRemoteUpdate is called when the value of a characteristic is updated from an http request. For example a paired controller (iPhone) is turning on a light bulb and sets the On characteristics to `true`.
- OnValueUpdate is called when the value of a characteristics is updated. This might happen remotely (as in OnValueRemoteUpdate) or locally (for example your program is updating the value of a characteristic)
- OnSetRemoteValue is called right before a characteristic value is updated from an http request. This method allows you to prevent updating the value of the characteristic. It allows lets you return an error, if the value should not be updated. This method is useful it cases where you want to propagate the new value to a different system – for example over the network. If the other system is down, you can return an error which then results in an error in HomeKit.

These methods are very similar but serve a different purpose. 

Anything else you need help with?

**Comment by ferllings** [comment]
Thanks that's very helpfull !
