### ISSUE TITLE
Add interfaces on dnssd service

### ISSUE THREAD

**Issue by stefanopulze** [brutella/hap#18]
I suggest a new configuration value of the server to the dnssd service.
The new value is a list of interface names used by dnsssd service to publish the correct ip when it exposes the hap service.

The problem, for me, is that the raspberry where I deploy the hap server has a multiple interfaces: one for the lan and the second for the iot devices. My firewall configuration blocks all the iot traffic (192.168.20.0/24) to the regular lan (192.168.1.00/24).  
When the dnssd server goes up it uses all the interfaces on the device so the pairing with the iphone fails.
I suppose that when the iphone starts pairing it uses the iot lan ip, that cannot reach the lan networks.

<img width="258" alt="Screenshot 2023-01-02 alle 15 28 28" src="https://user-images.githubusercontent.com/5228670/210244680-92ebbd83-6f94-467f-bc1c-35f705fe444a.png">

The change I suggest is to add the new value to the server configuration that will be used on `dnssd.Config`.`Ifaces` into the file `server.go` at line 479.

**Comment by brutella** [comment]
Great idea. Please checkout branch `ifaces`, which adds the field `Ifaces` to the server struct.

**Comment by stefanopulze** [comment]
Thanks for modifying so fast. I have just tryed but it doesn’t work.
I have investigated more deeper and I found that the problem is in dnssd project. There is a open issue: https://github.com/brutella/dnssd/issues/33.

I forked the dnssd project and made the fix. I tested in my local environment and it works well, but before I create a merge request it would be better to test it more.

**Comment by brutella** [comment]
This should be fixed in v0.0.25
