### ISSUE TITLE
pairings.go:41: tlv8: EOF

### ISSUE THREAD

**Issue by LUJUNQUAN** [brutella/hap#21]
Hello:
    When I was using the latest version of development, I found that if my home app added a bridge and device, when I removed the bridge, the following message would be displayed:
INFO 2023/02/08 17:26:10 pairings.go:41: tlv8: EOF
    At this point, it appears in my home application that the bridge is unbound; however, it is not  the home application can no longer discover the bridge; and there is still a.pairing file in the db folder of the application directory. This issue appears after version 0.0.18
I hope you can help me answer this question.
It's a great project

**Comment by brutella** [comment]
Thanks for your report. Fixed by 340cbe4 which is available in v0.0.23
