### ISSUE TITLE
Problem pairing: Unable to Add Accessory (out of compliance).

### ISSUE THREAD

**Issue by hubertat** [brutella/hap#23]
Hi!

I've been using hc library for some time now - many thanks for creating and maintaining it! :)

Recently I migrated my application from hc to hap and after doing that I receive following error when I try to add new accessory to my Home:

> Unable to Add Accessory
> Accessory is out of compliance.

Something I newer saw before in HomeKit.

I tried to set `hap.Server.MfiCompliant` to `true` - after doing that, connecting to bridge is not finishing, after few minutes I see 'Accessory is not reachable' error.

I upgraded my Home to new architecture in iOS 16, maybe that could be the issue?
I'll appreciate any help with that issue.

Hubert

**Comment by brutella** [comment]
Are you using custom characteristics in your HomeKit project?
Could you post a link to you HomeKit project so that I can take a closer look?

**Comment by brutella** [comment]
Closed due to inactivity...
