### ISSUE TITLE
Getting access to C.setValue()?

### ISSUE THREAD

**Issue by geekman** [brutella/hap#25]
Thanks for writing hc/hap! I'm writing a bridge using hap, similar to hkknx (I think). After creating a Service instance, for example `service.NewTemperatureSensor()`, I'm then storing the relevant mapped characteristic `s.CurrentTemperature.C` into something like a `map[string]*characteristic.C` to manage centrally. When I receive an update to the temperature, I would like to translate and store the value into the characteristic. I believe it's easier to `switch` on `c.Format` than to figure out if it's cast-able to a `Bool` or `Int`.

While I can set the value directly into `c.Val`, I lose the various functions performed by `c.setValue()`, such as the "type conversion", clampFloat/Int, and the firing of `valUpdateFuncs` which I believe is what sends notifications to clients. If I call `c.SetValueRequest()` it will fail in this case because the temperature characteristic is not writable.

Is trying to call `c.setValue()` the right thing to do here? Am I missing something? One possible solution might be to change the check in `SetValueRequest` to `!c.IsWritable && req != nil` to only block writing for remote requests.

**Comment by brutella** [comment]
@geekman Does 4d1fbc1 fix this issue?

**Comment by geekman** [comment]
Yes, that should solve the issue. Thanks!
