### ISSUE TITLE
[Question] Code for alarm device

### ISSUE THREAD

**Issue by ferllings** [brutella/hap#26]
Hello,
I'm thinking of doing a homekit bridge for my alarm.
Is it possible with the homekit protocol (and hap) to ask for a code, to disarm the alarm?
Is there a way to secure a service?

Thanks

**Comment by brutella** [comment]
> Is it possible with the homekit protocol (and hap) to ask for a code, to disarm the alarm?

Nope

> Is there a way to secure a service?

In general security devices are already secured by HomeKit. You can only disarm an alarm devices if your iOS devices (or Apple Watch) is unlocked.

**Comment by ferllings** [comment]
Thanks, I just wanted a confirmation.
