### ISSUE TITLE
Safer file & dir permissions for FsStore

### ISSUE THREAD

**Issue by geekman** [brutella/hap#28]
Currently the permissions used in `fs.go` for directories are `0755` and files are at `0666`. This would allow everyone to read, and also to write to (!!), the created files and directories, which is undesirable, especially since it contains the encryption/pairing keys.

A safer default for the directories would be `0750` and for files it would be `0640`. This would allow the user running the hap process to read & write to these files, only read access for the group, and nobody else.

**Comment by brutella** [comment]
The changes in 4329b4f should fix this issue.

**Comment by geekman** [comment]
Thanks! Actually this commit saved me from filing another bug:

```
store.Set("file", []byte("abcdef"))
store.Set("file", []byte("123"))
```

In this case `store.Get("file")` will actually return `123def` because `OpenFile()` doesn't truncate the file first. `os.WriteFile` says it will truncate the file if it exists, so that fixes the bug. 

I encountered this bug because my JSON persisted into the store was getting corrupted, which was weird because it came directly from `json.Marshal`.
