### ISSUE TITLE
Returning "comm failure" for 1 characteristic renders entire bridge unresponsive

### ISSUE THREAD

**Issue by geekman** [brutella/hap#30]
I'm not sure if this behaviour is expected, but I'm trying to mark some accessories on my bridge as "no response" if they have not been seen in a while. I set a `ValueRequestFunc` and return `JsonStatusServiceCommunicationFailure` for _that_ particular device, hoping that iOS will mark that device as not responding, but iOS ended up marking the entire bridge and all its accessories as not responding.

Test code is here:
```go
package main

import (
	"github.com/brutella/hap"
	"github.com/brutella/hap/accessory"
	"github.com/brutella/hap/service"

	haplog "github.com/brutella/hap/log"

	"context"
	"fmt"
	"net/http"
)

func main() {
	store := hap.NewFsStore("./db")
	bridge := accessory.NewBridge(accessory.Info{Name: "hap test bridge"})

	s1 := accessory.New(accessory.Info{Name: "Temp Sensor 1"}, accessory.TypeSensor)
	s1.AddS(service.NewTemperatureSensor().S)

	s2 := accessory.New(accessory.Info{Name: "Temp Sensor 2"}, accessory.TypeSensor)
	temp := service.NewTemperatureSensor()
	// return comms failure on sensor 2
	temp.CurrentTemperature.ValueRequestFunc = func(req *http.Request) (any, int) {
		return temp.CurrentTemperature.Val, hap.JsonStatusServiceCommunicationFailure
	}
	s2.AddS(temp.S)

	server, err := hap.NewServer(store, bridge.A, s1, s2)
	if err != nil {
		panic(err)
	}

	fmt.Println("pin 0010-2003")

	haplog.Debug.Enable()

	server.ListenAndServe(context.Background())
}
```

In Home app, it looks like this:
![screenshot](https://github.com/brutella/hap/assets/563153/533fa7b4-204a-4a68-aca0-3177f0f565d0)

When I remove the code to return comm failure, both accessories are accessible.

In trying to debug this issue I used `haplog.Debug.Enable()` but it doesn't seem to show any requests that iOS is making that it would know the device is no responding. Or maybe I'm just not familiar enough with the HAP protocol. I've added the log here:

```
$ go run t.go
pin 0010-2003
DEBUG 2023/05/15 08:26:24 server.go:228: listening at [::]:32849
DEBUG 2023/05/15 08:26:29 logger.go:161: "POST http://hap_test_bridge._hap._tcp.local/pair-verify HTTP/1.1" from :49240 - 200 140B in 2.017539ms
DEBUG 2023/05/15 08:26:29 logger.go:161: "POST http://hap_test_bridge._hap._tcp.local/pair-verify HTTP/1.1" from :49240 - 200 3B in 1.338635ms
DEBUG 2023/05/15 08:26:29 accessories.go:25: {"accessories":[{"aid":1,"services":[{"iid":1,"type":"3E","characteristics":[{"iid":2,"type":"14","perms":["pw"],"format":"bool"},{"iid":3,"type":"20","perms":["pr"],"format":"string","value":"-"},{"iid":4,"type":"21","perms":["pr"],"format":"string","value":"-"},{"iid":5,"type":"23","perms":["pr"],"format":"string","value":"hap test bridge"},{"iid":6,"type":"30","perms":["pr"],"format":"string","value":"-"},{"iid":7,"type":"52","perms":["pr"],"format":"string","value":"-"}]}]},{"aid":2,"services":[{"iid":1,"type":"3E","characteristics":[{"iid":2,"type":"14","perms":["pw"],"format":"bool"},{"iid":3,"type":"20","perms":["pr"],"format":"string","value":"-"},{"iid":4,"type":"21","perms":["pr"],"format":"string","value":"-"},{"iid":5,"type":"23","perms":["pr"],"format":"string","value":"Temp Sensor 1"},{"iid":6,"type":"30","perms":["pr"],"format":"string","value":"-"},{"iid":7,"type":"52","perms":["pr"],"format":"string","value":"-"}]},{"iid":8,"type":"8A","characteristics":[{"iid":9,"type":"11","perms":["pr","ev"],"format":"float","value":0,"unit":"celsius","maxValue":100,"minValue":0,"minStep":0.1}]}]},{"aid":3,"services":[{"iid":1,"type":"3E","characteristics":[{"iid":2,"type":"14","perms":["pw"],"format":"bool"},{"iid":3,"type":"20","perms":["pr"],"format":"string","value":"-"},{"iid":4,"type":"21","perms":["pr"],"format":"string","value":"-"},{"iid":5,"type":"23","perms":["pr"],"format":"string","value":"Temp Sensor 2"},{"iid":6,"type":"30","perms":["pr"],"format":"string","value":"-"},{"iid":7,"type":"52","perms":["pr"],"format":"string","value":"-"}]},{"iid":8,"type":"8A","characteristics":[{"iid":9,"type":"11","perms":["pr","ev"],"format":"float","unit":"celsius","maxValue":100,"minValue":0,"minStep":0.1}]}]}]}
DEBUG 2023/05/15 08:26:29 logger.go:161: "GET http://hap_test_bridge._hap._tcp.local/accessories HTTP/1.1" from :49240 - 200 1744B in 1.573594ms
```

I assumed that it would call `GET /characteristics` and that is where the `ValueRequestFunc` can be called, but it seems to only call `GET /accessories` and from that it somehow knows the bridge is unresponsive?

On a functioning bridge, it seems to call `PUT /characteristics`  next, to register callbacks for the value changes I think.

**Comment by brutella** [comment]
The Apple Home app shows "No Response" when it has no network connection to a specific accessory. 

If an accessory is managed by a bridge, and HomeKit doesn't get a network connection to one of the bridged accessories, it marks the whole bridge as not accessible. (I haven't tested this myself but it seems reasonable.)

One way to handle the case where a specific accessory is not accessible is to remove the accessory from the bridge. But there are some things you have to consider.

- If you add and remove accessories over time, you have to make sure that their corresponding IDs are the same. HomeKit identifies accessory by their ids and expects that an accessory has the same id the next time the bridge is accessible. You will have to do some kind of mapping between an accessories and ids.
- `hap` currently doesn't support removing accessory dynamically while the bridge is running. You will have to recreate the list of accessory and use a new bridge instance programmatically when removing an accessory. I'm doing the same in my projects and it works perfectly.

**Comment by geekman** [comment]
Alright I've managed to trace through the code using a `runtime/debug.PrintStack()` at `ValueRequestFunc` and figured it out. I found it hard to believe that something like a Philips Hue hub would not be able to signal to iOS that only a few bulbs are unreachable and takes down the entire hub with it.

Apparently there was a call to `ValueRequestFunc` as part of `C.MarshalJSON()`. The reason why iOS stopped at `GET /accessories` was because the returned JSON was "malformed", at least according to Apple's parsing. `/accessories` will call `*A.MarshalJSON` then `*S.MarshalJSON`, then ultimately to `*C.MarshalJSON`. Here, "value" is filled only on success:

https://github.com/brutella/hap/blob/040bd95eebde8dde939ebaae22377c91f4b6820d/characteristic/c.go#L288-L290

But in testing, **"value" needs to be present and cannot be null**, so it can only be a dummy value.

After that is fixed, iOS continues on to call `PUT /characteristics` as I described above.

Next, the multi-status 207 return is also malformed. ``"status": 0`` must be explicit, it cannot be omitted. Additionally, `"value"` must be omitted here, since it is an error. 

Applying these 2 fixes solved the issue:

```patch
$ git diff
diff --git a/characteristic/c.go b/characteristic/c.go
index 0f1c61c..8b3b415 100644
--- a/characteristic/c.go
+++ b/characteristic/c.go
@@ -287,6 +287,8 @@ func (c *C) MarshalJSON() ([]byte, error) {
                // 2022-03-21 (mah) FIXME provide a http request instead of nil
                if v, s := c.ValueRequest(nil); s == 0 {
                        d.Value = &V{v}
+               } else {
+                       d.Value = &V{c.Val} // dummy "zero" value
                }
        }

diff --git a/characteristics.go b/characteristics.go
index 1f6f72d..3ed757c 100644
--- a/characteristics.go
+++ b/characteristics.go
@@ -14,7 +14,7 @@ import (
 type characteristicData struct {
        Aid   uint64      `json:"aid"`
        Iid   uint64      `json:"iid"`
-       Value interface{} `json:"value"`
+       Value interface{} `json:"value,omitempty"`

        // optional values
        Type        *string     `json:"type,omitempty"`
@@ -89,6 +89,7 @@ func (srv *Server) getCharacteristics(res http.ResponseWriter, req *http.Request
                        cdata.Status = &s
                } else {
                        cdata.Value = v
+                       cdata.Status = new(int) // 0
                }

                if meta {
```
As I'm not too familiar with the code, I don't know if there will be any side effects from these changes, but it works now. Only 1 sensor will be marked as "no response", while all other accessories function normally.

**Comment by brutella** [comment]
Thanks for clarifying your findings.

This issue might be resolved by just removing the `omitempty` option from the `C.Value` and `characteristicData.Status` fields and adding `omitempty`to `characteristicData.Value`. Could you please try that?

**Comment by brutella** [comment]
> Do you want me to submit a PR that fixes the bugs?

That would be great. 👍
