### ISSUE TITLE
Accessory not showing up for pairing

### ISSUE THREAD

**Issue by korgoth** [brutella/hap#33]
I am quite new to this library and am just trying the very basic example provided in the Readme

package main

import (
	"github.com/brutella/hap"
	"github.com/brutella/hap/accessory"

	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	// Create the switch accessory.
	a := accessory.NewSwitch(accessory.Info{
		Name: "Lamp",
	})

	// Store the data in the "./db" directory.
	fs := hap.NewFsStore("./db")

	// Create the hap server.
	server, err := hap.NewServer(fs, a.A)
	if err != nil {
		// stop if an error happens
		log.Panic(err)
	}

	// Setup a listener for interrupts and SIGTERM signals
	// to stop the server.
	c := make(chan os.Signal)
	signal.Notify(c, os.Interrupt)
	signal.Notify(c, syscall.SIGTERM)

	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		<-c
		// Stop delivering signals.
		signal.Stop(c)
		// Cancel the context to stop the server.
		cancel() 
	}()

	// Run the server.
	server.ListenAndServe(ctx)
}

The code runs without any errors in the console, but i dont see any accessory waiting to be paired in the Home app? 

I am running the code on macOS if that matters. What am i doing wrong? 

P.S. After i run "go run main.go" - macOS prompts me if i would allow the program to accept incoming connections, so i guess the server is properly started, but still nothing appears in the Home app. Even if i try to enter the code manually - nothing happens

**Comment by brutella** [comment]
This may be related to #34
