### ISSUE TITLE
Can't use Thermostat with custom min temperature

### ISSUE THREAD

**Issue by sivakov512** [brutella/hap#38]
Hi!
When I create Thermostat accessory and set target temperature min value to 17 then I can't add it to Home app - it return error "Accessory is out of compliance". Can you help me please how to handle it?

**Comment by brutella** [comment]
The HomeKit Accessory Protocol specifies a minimum value of 17 and max value of 38 for the target temperature. It seems like you cannot change that.

**Comment by sivakov512** [comment]
Okay… Where did you found these info?

**Comment by brutella** [comment]
This is documented in the HAP (HomeKit Accessory Protocol) document. 

Unfortunately Apple removed this document from the developer website. https://developer.apple.com/apple-home/
