### ISSUE TITLE
dynamically adding/removing accessory from a bridge

### ISSUE THREAD

**Issue by mow** [brutella/hap#39]
I couldn't find a way to add/remove accessory to/from a bridge accessory, is it possible to dynamically add/remove a accessory to/from a bridge?

**Comment by brutella** [comment]
There is currently no way to add and remove accessories while the server is running. I recommend to teardown the running server and create a new one with the updated list of accessories. 

Keep in mind that the accessory ids must be the same across restarts/reboots. This means that when you remove and then add the same accessory again, it must have the same id as before.
