### ISSUE TITLE
Usage example from readme cannot gracefully exit the app

### ISSUE THREAD

**Issue by mcsakoff** [brutella/hap#41]
OS: MacOS Sonoma, MacOS Ventrura
hap v0.0.27

Calling `cancel()` doesn't make it gracefully exit from `server.ListenAndServe(ctx)`.

I added some logging
```go
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		<-c
		// Stop delivering signals.
		signal.Stop(c)
		println("stopping")
		// Cancel the context to stop the server.
		cancel()
	}()

	// Run the server.
	println("starting")
	if err = server.ListenAndServe(ctx); err != nil {
		println(err.Error())
	}
	println("stopped")
```

Result:

```
starting
^Cstopping
^C
```

Application exits with return value 130 after second Crtl+C.

PS: Linux is not affected

**Comment by mcsakoff** [comment]
**Workaround**

Provide one specific interface:
```go
server.Ifaces = []string{"en0"}
```

**Comment by brutella** [comment]
This may be fixed by https://github.com/brutella/dnssd/pull/43

Please check out hap v0.0.28 which includes this change.

**Comment by mcsakoff** [comment]
hap v0.0.28
dnssd v1.2.10

Fixed. Discovery works fine.
I suppose that #33 and #34 can be closed as well.
