### ISSUE TITLE
How to create new accessory or use Air Conditioner accessory

### ISSUE THREAD

**Issue by MyNewFlint** [brutella/hap#45]
I want to control Air Conditioner. But there is not Air Conditioner accessory. 
I only find the demo code .

a := accessory.NewSwitch(accessory.Info{
		Name: "Lamp",
	})

thank you for your help

**Comment by brutella** [comment]
You can use a [cooler](https://github.com/brutella/hap/blob/master/service/cooler.go) service for an air conditioner and wrap it in an accessory struct like this.

```go
info := accessory.Info{Name: "Air Conditioner"}
a := accessory.New(info, accessory.TypeAirConditioner)

cooler := service.NewCooler()
a.AddS(cooler.S)

s, err := hap.NewServer(hap.NewFsStore("./db"), a)
```

**Comment by MyNewFlint** [comment]
Thank you for your reply. Use your code I could have a cooler device in APP. But the Air Conditioner have 5 characteristics, like on/off, mode(cold,hot,wet,wind), fan(low,mid,high,auto), CurrentTemperature, TargetTemperature. I do not know how to make this in a new accessory
