### ISSUE TITLE
Thermostat need a struct value for current humidity.

### ISSUE THREAD

**Issue by p000** [brutella/hap#48]
- [ ] Provide an option to set current humidity. (same as current room temperature)
- [ ] Provide a function to update humidity on remote update from the device.

Please let me know if this feature to be supported.

I can try contribute as well, with your guidance.

**Comment by brutella** [comment]
If you need specific characteristics for an accessory, you can add them yourself. For example if you need the current humidity for a thermostat, you can create your custom thermostat service and add the humidity as a new property.

```go
type CustomThermostat struct {
	*service.Thermostat

	CurrentHumidity *characteristic.CurrentRelativeHumidity
}

func NewCustomThermostat() *CustomThermostat {
	return &CustomThermostat{
		Thermostat:      service.NewThermostat(),
		CurrentHumidity: characteristic.NewCurrentRelativeHumidity(),
	}
}

func main() {
	info := accessory.Info{ Name: "Thermostat" }
	a := accessory.New(info, accessory.TypeThermostat)

	// Add your custom thermostat service
	thermostat := NewCustomThermostat()
	a.AddS(thermostat.S)

	// Update the relative humidity
	thermostat.CurrentHumidity.SetValue(60)
	...
}
```

**Comment by p000** [comment]
@brutella - Thanks for the sample. It worked and you are awesome 👍🏼 😍
