### ISSUE TITLE
Manually setting the accessory ID causes accessory to be unresponsive

### ISSUE THREAD

**Issue by annismckenzie** [brutella/hap#50]
I'm working on an integration between HomeKit and KNX at home. This all works really really well and your library is a joy to work with! 🎉

I have my bridge deployed to a local k3s cluster and I'd like to make it possible to move the bridge between machines. In theory that should be possible, as you mention in the readme (https://github.com/brutella/hap#multiple-accessories). Ideally, if the state is accessible and the accessory IDs don't change I should be good.

However, as soon as I manually set an ID – even if the bridge only has a single accessory, the pairing apparently doesn't finish and the Home app lists the accessory as unresponsive. When I drop that single line setting the accessory ID, clear the local state (in `./fs`) and re-add the bridge, everything works.

Do you have any idea what could be causing this? I've read about the disaster with the Home architecture change in iOS 16.2. I migrated to the new architecture a long time ago – but I also didn't have any Matter devices so it went smoothly without any issues. I've tried unplugging all of the home hubs (HomePods, an Apple TV) and only left the iPad Pro on but that didn't have any impact. I keep all the devices up to date (everything on 17.2 as of this writing).

Where should I be looking to debug this? Thank you again for this awesome project.

**Comment by brutella** [comment]
The server stores the data in a location on the filesystem. (Specified by the `store` argument in [hap.NewServer(...)](https://github.com/brutella/hap/blob/fc673a84ecb97e4572ada94a9c359a34f83a9099/server.go#L85C11-L85C11))

Are copying the content of this folder also the new location?

**Comment by brutella** [comment]
Oh and btw, if you are interested in controlling KNX devices with HomeKit, you should checkout [hkknx](https://hochgatterer.me/hkknx/).

**Comment by annismckenzie** [comment]
> Oh and btw, if you are interested in controlling KNX devices with HomeKit, you should checkout [hkknx](https://hochgatterer.me/hkknx/).

I know about that one and even tried it out. I just… couldn't get it to work and needed to get my hands dirty building it myself. 😅

> The server stores the data in a location on the filesystem. (Specified by the `store` argument in [hap.NewServer(...)](https://github.com/brutella/hap/blob/fc673a84ecb97e4572ada94a9c359a34f83a9099/server.go#L85C11-L85C11))
> 
> Are copying the content of this folder also the new location?

I should have phrased this differently. Me adding stable and known accessory IDs is only the preparation for when I want to move the installation. But this problem doesn't appear after the move to a different machine, it happens when I try to assign IDs and add the bridge for the first time (no state, any previous bridges removed from my HomeKit installation). Does that make sense?

**Comment by brutella** [comment]
Please check if the first accessory that you add to the server has the id `1` and not `0`.
