### ISSUE TITLE
Dynamic device resolution

### ISSUE THREAD

**Issue by jaedle** [brutella/hap#6]
Hey @brutella :wave: 

First of I all would like to thank you! I just started playing around with this library and I finally added some glue code to [my own library](https://github.com/jaedle/golang-tplink-hs100) and was able to create a simple home-automation app with device auto discovery within an hour! :clap: 

Also the possibility to add an external data-storage is great, so I can easily run this within a container and won't have to worry about local filesystems. :clap: 

Nevertheless it seems like I have run into a problem:I am trying to autodetect my devices. 

I am doing something like that:

```go
devices, _ := hs100.Discover("192.168.2.0/24", configuration.Default().WithTimeout(3*time.Second))
var plugs []*accessory.A
for _, d := range devices {
     plugs = append(plugs, toPlug(d).A)
}

server, err := hap.NewServer(fs, accessory.NewBridge(accessory.Info{
     Name: "bridge",
}).A, plugs...)

...

func toPlug(d *hs100.Hs100) *accessory.Switch {
	info, err := d.GetInfo()
	if err != nil {
		panic(err)
	}
	
	result := accessory.NewSwitch(accessory.Info{
		Name:         info.Name,
		SerialNumber: info.DeviceId,
	})

	result.Switch.On.ValueRequestFunc = func(request *http.Request) (value interface{}, code int) {
		if isOn, err := d.IsOn(); err != nil {
			// please ignore the wrong return code
                        return false, -1
		} else {
			return isOn, 0
		}
	}

	result.Switch.On.OnSetRemoteValue(func(v bool) error {
		if v == true {
			return d.TurnOn()
		} else {
			return d.TurnOff()
		}
	})
	
	return result
}

```

This auto-creates the accessories with a consistent name + serialnumber (idempotent action). Sadly the order of the detected devices is not idempotent as there is no order and devices may be added or removed.

When restarting the services, I have noticed that the name of the Home-App was not matching to the actor anymore. I believe that's because of the [id generation of the accessories](https://github.com/brutella/hap/blob/a10ea561c5b10d9e78fabc3df5e95123a9986e1f/server.go#L238).

I tried to work my way around this by manually generating a unique accessory id before starting the server, but that feels like I am having to much knowledge of what is going on inside of hap.

Maybe you can share some thoughts about potential solutions or maybe my use-case is just unsupported.

Thanks and best regards,
Dennis

**Comment by brutella** [comment]
> When restarting the services, I have noticed that the name of the Home-App was not matching to the actor anymore. I believe that's because of the [id generation of the accessories](https://github.com/brutella/hap/blob/a10ea561c5b10d9e78fabc3df5e95123a9986e1f/server.go#L238).

Yes, that's exactly the reason why the names didn't match anymore.

> I tried to work my way around this by manually generating a unique accessory id before starting the server, but that feels like I am having to much knowledge of what is going on inside of hap.

That's totally fine. The `Id` field is public and should be used for this reason. HomeKit expects that the ids of accessory are always the same. If you dynamically add accessory to a bridge, you have to make sure that the ids are the same.

**Comment by jaedle** [comment]
Thanks for fast reply :+1: 

If that's perfectly fine, then I will make sure to generate unique ids for before passing accessories to hap.

I have one more question, but I am not sure, if this blows the scope if this issue. If so, please tell me.

I have been trying out how to best handle device device appearance / disappearance. Any chance for a _hot-reloading_ feature within hap? Right now, I have to manually kill the server and restart it.

**Comment by brutella** [comment]
> I have been trying out how to best handle device device appearance / disappearance. Any chance for a _hot-reloading_ feature within hap for the accessories? Right now, I have to manually kill the server and restart it.

That's the best way to do it.
